### Site metadata ###

site_name: Centro de Documentación
site_description: Documentación consolidada de todos los proyectos
site_url: https://alexaiedev.github.io/Repo_docs/

repo_url: https://github.com/AlexaieDev/Repo_docs
edit_uri: edit/main/docs/docs

### Build settings ###

theme: readthedocs

### Plugins ###

plugins:
  - search
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      nav_repos:
        - name: Best Practices
          import_url: 'https://github.com/AlexaieDev/best_practices?branch=main'
          imports: [ README.md, docs/* ]

nav:
  - Inicio: index.md
  - Proyectos:
      - Índice de Proyectos: proyectos/index.md
      - Proyecto 1 - Sistema de Gestión:
          - Resumen: proyectos/proyecto-1/index.md
          - Getting Started: proyectos/proyecto-1/getting-started/index.md
          - API Reference: proyectos/proyecto-1/api/index.md
          - Guías: proyectos/proyecto-1/guides/index.md
          - Ejemplos: proyectos/proyecto-1/examples/index.md
      - Proyecto 2 - E-Commerce:
          - Resumen: proyectos/proyecto-2/index.md
          - Getting Started: proyectos/proyecto-2/getting-started/index.md
          - API Reference: proyectos/proyecto-2/api/index.md
          - Guías: proyectos/proyecto-2/guides/index.md
          - Ejemplos: proyectos/proyecto-2/examples/index.md
      - Proyecto 3 - API Integraciones:
          - Resumen: proyectos/proyecto-3/index.md
          - Getting Started: proyectos/proyecto-3/getting-started/index.md
          - API Reference: proyectos/proyecto-3/api/index.md
          - Guías: proyectos/proyecto-3/guides/index.md
          - Ejemplos: proyectos/proyecto-3/examples/index.md
  - Proyectos Externos:
      - Best Practices: '!import https://github.com/AlexaieDev/best_practices?branch=main'
  - Guías MkDocs:
      - Acerca de MkDocs: about-mkdocs.md
      - Tutorial:
          - TL;DR: tutorial/tldr.md
          - Installation: tutorial/installation.md
          - Set up project: tutorial/setup-project.md
          - Advanced: tutorial/advanced.md
          - Usage: tutorial/usage.md
          - Deploy: tutorial/deploy.md
