### Site metadata ###

site_name: Centro de Documentación
site_description: Documentación consolidada de todos los proyectos
site_url: https://alexaiedev.github.io/Repo_docs/

repo_url: https://github.com/AlexaieDev/Repo_docs
edit_uri: edit/main/docs/docs

### Build settings ###

theme: readthedocs

### Plugins ###

plugins:
  - search
  - multirepo:
      cleanup: false
      nav_repos:
        - name: best-practices
          import_url: 'https://github.com/AlexaieDev/best_practices?branch=main'
        - name: open-agentic-framework
          import_url: 'https://github.com/oscarvalenzuelab/open_agentic_framework?branch=main'
        - name: sbom-analysis-agentic
          import_url: 'https://github.com/oscarvalenzuelab/sbom_analysis_using_agentic?branch=main'
        - name: purl2src
          import_url: 'https://github.com/SemClone/purl2src?branch=main'
        - name: osslili
          import_url: 'https://github.com/SemClone/osslili?branch=main'
        - name: upmex
          import_url: 'https://github.com/SemClone/upmex?branch=main'
        - name: binarysniffer
          import_url: 'https://github.com/SemClone/binarysniffer?branch=main'
        - name: src2purl
          import_url: 'https://github.com/SemClone/src2purl?branch=main'
        - name: purl2notices
          import_url: 'https://github.com/SemClone/purl2notices?branch=main'
        - name: vulnq
          import_url: 'https://github.com/SemClone/vulnq?branch=main'
        - name: ospac
          import_url: 'https://github.com/SemClone/ospac?branch=main'
        - name: ossnotices
          import_url: 'https://github.com/SemClone/ossnotices?branch=main'

nav:
  - Inicio: index.md
  - Proyects:
      - Best Practices:
          - Overview: best-practices/README.md
          - Contributing: best-practices/CONTRIBUTING.md
          - Security: best-practices/SECURITY.md
      - Open Agentic Framework:
          - Overview: open-agentic-framework/README.md
      - SBOM Analysis Using Agentic:
          - Overview: sbom-analysis-agentic/README.md
      - SemClone Tools:
          - purl2src: purl2src/README.md
          - osslili: osslili/README.md
          - upmex: upmex/README.md
          - binarysniffer: binarysniffer/README.md
          - src2purl: src2purl/README.md
          - purl2notices: purl2notices/README.md
          - vulnq: vulnq/README.md
          - ospac: ospac/README.md
          - ossnotices: ossnotices/README.md
  - Guías MkDocs:
      - Acerca de MkDocs: about-mkdocs.md
      - Tutorial:
          - TL;DR: tutorial/tldr.md
          - Installation: tutorial/installation.md
          - Set up project: tutorial/setup-project.md
          - Advanced: tutorial/advanced.md
          - Usage: tutorial/usage.md
          - Deploy: tutorial/deploy.md



  # - Proyectos:
  #     - Índice de Proyectos: proyectos/index.md
  #     - Proyecto 1 - Sistema de Gestión:
  #         - Resumen: proyectos/proyecto-1/index.md
  #         - Getting Started: proyectos/proyecto-1/getting-started/index.md
  #         - API Reference: proyectos/proyecto-1/api/index.md
  #         - Guías: proyectos/proyecto-1/guides/index.md
  #         - Ejemplos: proyectos/proyecto-1/examples/index.md
  #     - Proyecto 2 - E-Commerce:
  #         - Resumen: proyectos/proyecto-2/index.md
  #         - Getting Started: proyectos/proyecto-2/getting-started/index.md
  #         - API Reference: proyectos/proyecto-2/api/index.md
  #         - Guías: proyectos/proyecto-2/guides/index.md
  #         - Ejemplos: proyectos/proyecto-2/examples/index.md
  #     - Proyecto 3 - API Integraciones:
  #         - Resumen: proyectos/proyecto-3/index.md
  #         - Getting Started: proyectos/proyecto-3/getting-started/index.md
  #         - API Reference: proyectos/proyecto-3/api/index.md
  #         - Guías: proyectos/proyecto-3/guides/index.md
  #         - Ejemplos: proyectos/proyecto-3/examples/index.md
