### Site metadata ###

site_name: Centro de Documentación
site_description: Documentación consolidada de todos los proyectos
site_url: https://alexaiedev.github.io/Repo_docs/

repo_url: https://github.com/AlexaieDev/Repo_docs
edit_uri: edit/main/docs/docs

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md
  - About MkDocs: about-mkdocs.md
  - Tutorial:
      - TL;DR: tutorial/tldr.md
      - Installation: tutorial/installation.md
      - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      - Deploy: tutorial/deploy.md
